### ISSUE TITLE
.proto protobuf files

### ISSUE THREAD

**Issue by xloem** [Enigma644/ix-muse-player#1]
Hey, I haven't found an updated .proto specification for the .muse files your app produces.   Where do I look for this?

I found interaxon's archived developer site which has the protobuf file, but it has only the files with the version field set to 1, and yours have this field set to 2.  What has changed?

**Comment by Enigma644** [comment]
If you search Google for "Muse_v2.proto" you will find their 2014 dev site with a download for the v2 proto file here https://sites.google.com/a/interaxon.ca/muse-developer-site/data-files

Please note that this repo was not developed by me! I only edited a couple of files to add UTF8 support.

**Comment by xloem** [comment]
Oh, I didn't know you didn't write it!

I actually came from the site you linked.  They state:

>  "Version" is version number. Currently there is only one version, version "1". 

Your app is writing files with version=2.  Maybe this is a bug or maybe interaxon's site isn't up to date.

**Comment by xloem** [comment]
Oh, I didn't know you didn't write it!

I actually came from the site you linked.  They state:

>  "Version" is version number. Currently there is only one version, version "1". 

Your app is writing files with version=2.  Maybe this is a bug or maybe interaxon's site isn't up to date.

**Comment by Enigma644** [comment]
> Oh, I didn't know you didn't write it!

It's in my readme, line 2: "Modified version of Interaxon's Muse Player" ;-)
This code used to be in their BitBucket (now removed) and was marked with an open source license, so I branched it to fix the UTF8 bug.

**Comment by Enigma644** [comment]
> Oh, I didn't know you didn't write it!

It's in my readme, line 2: "Modified version of Interaxon's Muse Player" ;-)
This code used to be in their BitBucket (now removed) and was marked with an open source license, so I branched it to fix the UTF8 bug.

**Comment by Enigma644** [comment]
> Oh, I didn't know you didn't write it!

It's in my readme, line 2: "Modified version of Interaxon's Muse Player" ;-)
This code used to be in their BitBucket (now removed) and was marked with an open source license, so I branched it to fix the UTF8 bug.

**Comment by xloem** [comment]
Sorry for the double-reply; I'm inferring you might have given three replies because I didn't mention my accidental double-reply, just quickly deleted it.

I'll sort out my version=1,version=2 thing as I bump into it.

So you know, some of us have been working a little into making other apps to access the muse.  I found the bluetooth gatt characteristics for the new breath/heartrate channels and added them to alexandrebarachant's python muse-lsl repository (on mobile or I'd link).  I also added android support to the bleak bluetooth python package, and submitted a pull reques to muse-lsl to add bleak as a bluetooth backend.  My attention's been shifting, but things slowly develop.

I emailed you long ago asking about open sourcing your app, and you replied that you needed the money too badly.  Sometimes I think an open source app could have a paid version and send funds to devs like you who have worked hard.  If the only version on the play store is the paid one, I imagine most users paying.

**Comment by Enigma644** [comment]
Cool.

Feel free to post that kind of thing on https://mind-monitor.com/forums/ and I'll help out where I can

| UUID                                 | Purpose          | 2 | 3 | S |
| ------------------------------------ | ---------------- | - | - | - |
| 273e0001-4c4d-454d-96be-f03bac821358 | SERIAL           | X | X | X |
| 273e0002-4c4d-454d-96be-f03bac821358 | SIGNAL_AUX_LEFT  | X | X | X |
| 273e0003-4c4d-454d-96be-f03bac821358 | SIGNAL_TP9       | X | X | X |
| 273e0004-4c4d-454d-96be-f03bac821358 | SIGNAL_FP1       | X | X | X |
| 273e0005-4c4d-454d-96be-f03bac821358 | SIGNAL_FP2       | X | X | X |
| 273e0006-4c4d-454d-96be-f03bac821358 | SIGNAL_TP10      | X | X | X |
| 273e0007-4c4d-454d-96be-f03bac821358 | SIGNAL_AUX_RIGHT | X | X | X |
| 273e0008-4c4d-454d-96be-f03bac821358 | DRL_REF          | X | X | X |
| 273e0009-4c4d-454d-96be-f03bac821358 | GYRO             | X | X | X |
| 273e000a-4c4d-454d-96be-f03bac821358 | ACCELEROMETER    | X | X | X |
| 273e000b-4c4d-454d-96be-f03bac821358 | BATTERY          | X | X | X |
| 273e000c-4c4d-454d-96be-f03bac821358 | MAGNETOMETER     |   | X | X |
| 273e000d-4c4d-454d-96be-f03bac821358 | PRESSURE         |   | X | X |
| 273e000e-4c4d-454d-96be-f03bac821358 | ULTRA_VIOLET     |   | X | X |
| 273e000f-4c4d-454d-96be-f03bac821358 | PPG_AMBIENT      |   | X | X |
| 273e0010-4c4d-454d-96be-f03bac821358 | PPG_IR           |   | X | X |
| 273e0011-4c4d-454d-96be-f03bac821358 | PPG_RED          |   | X | X |
| 273e0012-4c4d-454d-96be-f03bac821358 | THERMISTOR       |   |   | X |
