### ISSUE TITLE
Muse_v2.py : wrong message type for ACC_DROPPED_SAMPLES?

### ISSUE THREAD

**Issue by xloem** [Enigma644/ix-muse-player#2]
In comparing my protobuf file with yours, the biggest difference I found was this line:
https://github.com/Enigma644/ix-muse-player/blob/9e653f6dd8c34c629e5383ffa1849e38afb49055/src/Muse_v2.py#L1395

In my file, that should be `ACC_DROPPED_SAMPLES`, not `EEG_DROPPED_SAMPLES`, on the right

**Comment by Enigma644** [comment]
Probably, but no dropped samples info (any kind) is written by Mind Monitor to the ".Muse" files that this could read anyway, so this code will never get hit.

IX Muse Player was designed to stream ".Muse" protocol buffer files to IX Muse Lab and given that IX Muse Lab is no longer supported or available for download on the IX website, I don't think it's really worth maintaining this repository.

I'm not going to delete this repo, but I've no plans on updating it; especially for code that's untestable. ... Unless you have another use case for using this tool?

**Comment by xloem** [comment]
I was just trying to figure out how to handle my .muse files from Mind Monitor which have version=2 set.  I infer it's exactly the same as version=1 from the google sites archive.

I do get a lot of dropped samples with Mind Monitor.  Thanks for your app.
